---
title: "offline stocks"
author: "Mark Hancharik"
date: "10/6/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}

ptm1 <- proc.time()

 sp500names <- c( "ABT","ABBV","ACN","ATVI","AYI","ADBE","AMD","AAP",
 "AES","AET","AMG","AFL","A","APD","AKAM","ALK",
 "ALB","ARE","ALXN","ALGN","ALLE","AGN","ADS","LNT",
 "ALL","GOOGL", "GOOG","MO", "AMZN","AEE","AAL","AEP",
 "AXP","AIG","AMT","AWK","AMP","ABC","AME","AMGN", 
 "APH","APC","ADI","ANDV","ANSS","ANTM","AON","AOS",
 "APA","AIV","AAPL","AMAT","ADM","ARNC","AJG","AIZ",
 "T","ADSK","ADP","AZO","AVB","AVY","BHGE","BLL",
 "BAC","BK", "BCR","BAX","BBT","BDX","BRK-B", "BBY",
 "BIIB","BLK","HRB","BA", "BWA","BXP","BSX","BHF",
 "BMY","AVGO","BF-B","CHRW","CA", "COG","CDNS","CPB",
 "COF","CAH","CBOE","KMX","CCL","CAT","CBG","CBS",
"CELG","CNC","CNP","CTL","CERN","CF", "SCHW","CHTR", 
 "CHK","CVX","CMG","CB", "CHD","CI", "XEC","CINF", 
 "CTAS","CSCO","C","CFG","CTXS","CLX","CME","CMS",
 "COH","KO", "CTSH","CL", "CMCSA", "CMA","CAG","CXO",
 "COP","ED", "STZ","COO","GLW","COST","COTY","CCI",
"CSRA","CSX","CMI","CVS","DHI","DHR","DRI","DVA",
 "DE", "DLPH","DAL","XRAY","DVN","DLR","DFS","DISCA",
 "DISCK", "DISH","DG", "DLTR","D","DOV","DWDP","DPS",
 "DTE","DRE","DUK","DXC","ETFC","EMN","ETN","EBAY", 
 "ECL","EIX","EW", "EA", "EMR","ETR","EVHC","EOG",
 "EQT","EFX","EQIX","EQR","ESS","EL", "ES", "RE",
 "EXC","EXPE","EXPD","ESRX","EXR","XOM","FFIV","FB",
 "FAST","FRT","FDX","FIS","FITB","FE", "FISV","FLIR", 
 "FLS","FLR","FMC","FL", "F","FTV","FBHS","BEN",
 "FCX","GPS","GRMN","IT", "GD", "GE", "GGP","GIS",
 "GM", "GPC","GILD","GPN","GS", "GT", "GWW","HAL",
 "HBI","HOG","HRS","HIG","HAS","HCA","HCP","HP",
 "HSIC","HSY","HES","HPE","HLT","HOLX","HD", "HON",
 "HRL","HST","HPQ","HUM","HBAN","IDXX","INFO","ITW",
 "ILMN","IR", "INTC","ICE","IBM","INCY","IP", "IPG",
"IFF","INTU","ISRG","IVZ","IRM","JEC","JBHT","SJM",
 "JNJ","JCI","JPM","JNPR","KSU","K","KEY","KMB",
"KIM","KMI","KLAC","KSS","KHC","KR", "LB", "LLL",
 "LH", "LRCX","LEG","LEN","LVLT","LUK","LLY","LNC",
"LKQ","LMT","L","LOW","LYB","MTB","MAC","M", 
"MRO","MPC","MAR","MMC","MLM","MAS","MA", "MAT",
 "MKC","MCD","MCK","MDT","MRK","MET","MTD","MGM",
 "KORS" , "MCHP" , "MU", "MSFT","MAA","MHK","TAP","MDLZ", 
 "MON","MNST","MCO","MS", "MOS","MSI","MYL","NDAQ", 
 "NOV","NAVI","NTAP","NFLX" , "NWL","NFX","NEM","NWSA",
 "NWS","NEE","NLSN" , "NKE","NI", "NBL","JWN","NSC",
 "NTRS","NOC","NRG","NUE","NVDA","ORLY","OXY","OMC",
"OKE","ORCL","PCAR","PKG","PH", "PDCO","PAYX","PYPL", 
"PNR","PBCT" , "PEP","PKI","PRGO","PFE","PCG","PM",
 "PSX","PNW","PXD","PNC","RL", "PPG","PPL","PX",
 "PCLN","PFG","PG", "PGR","PLD","PRU","PEG","PSA",
 "PHM","PVH","QRVO" , "PWR","QCOM","DGX","Q","RRC",
 "RJF","RTN","O","RHT","REG","REGN","RF", "RSG",
 "RMD","RHI","ROK","COL","ROP","ROST","RCL","CRM",
 "SBAC","SCG","SLB","SNI","STX","SEE","SRE","SHW",
 "SIG","SPG","SWKS","SLG","SNA","SO", "LUV","SPGI", 
 "SWK","SBUX","STT","SRCL","SYK","STI","SYMC","SYF",
 "SNPS","SYY","TROW","TGT","TEL","FTI","TXN","TXT",
 "TMO","TIF","TWX","TJX","TMK","TSS","TSCO","TDG",
 "TRV","TRIP","FOXA","FOX","TSN","UDR","ULTA","USB",
 "UA", "UAA","UNP","UAL","UNH","UPS","URI","UTX",
 "UHS","UNM","VFC","VLO","VAR","VTR","VRSN","VRSK", 
 "VZ", "VRTX","VIAB","V","VNO","VMC","WMT","WBA",
 "DIS","WM", "WAT","WEC","WFC","HCN","WDC","WU",
 "WRK","WY", "WHR","WMB","WLTW","WYN","WYNN","XEL",
 "XRX","XLNX","XL")

sp500vars <- read.table("stocks_daily_var.txt", header=F)

sp500means <- read.table("stocks_daily_mean.txt", header=F)


#sp500names[which.min(sp500vars)]

choices  <- read.table("paired_choices.txt", header=F) # t(combn(sp500names,2))







stock_data <- cbind(sp500names, sp500vars, sp500means)
colnames(stock_data) <- c("symbol", "avg variance", "avg mean")

number_of_choices <- length(choices[,1]) # the number of ticker symbols
cat("# of choices =", number_of_choices)

calculated_values <- matrix(NaN, number_of_choices, 2, byrow=TRUE)




m_filter <- 0.03
v_filter <- 0.001

get_var <-function(m){
   

  
  for(i in 1:499){
    
    
  if(as.character(stock_data[i,1]) == m){
    if(stock_data[i,2]<v_filter){
      return(stock_data[i,2])
     }else{
     # cat(m,"=",sp500vars[i],"\n")
         return(1)
      }
    }
  } 

}


get_mean <-function(m){

  for(i in 1:499){
  
  if(as.character(stock_data[i,1]) == m){
      
     if(stock_data[i,3]<m_filter){
      return(stock_data[i,3])
     }else{
      #cat(m,"=",sp500means[i],"\n")
         return(1)
      }

    }
  } 

} 


num <- number_of_choices

for(i in 1:num){
  
   v1 <- get_var(choices[i,1])
   v2 <- get_var(choices[i,2])
  m1 <- get_mean(choices[i,1])
  m2 <- get_mean(choices[i,2])
   
   
  # cat("i = ", i, "\n")
  # cat("v1 = ", v1, "\n")
  # cat("m1 = ", m1, "\n")
  # cat("v2 = ", v2, "\n")
  # cat("m2 = ", m2, "\n")
  # added <- (v1 + v2)
 # cat(v1, "+", v2, "=",added,"\n")(
   #print(added)
   if(v1 != 1 & v2 != 1){
     calculated_values[i, 1] = (v1 + v2)
   }else{
     calculated_values[i, 1] = NaN
   }
  if(m1 != 1 & m2 != 1){
    calculated_values[i, 2] = (m1 + m2)/2
   }else{
     calculated_values[i, 2] = NaN
    # cat("i = ",i," m1=",m1, " m2 =",m2,"\n")
   }
  
  

}


#write.table(choices, file="paired_choices.txt", row.names=FALSE, col.names=FALSE)
write.table(calculated_values, file="calculated_values.txt", row.names=FALSE, col.names=FALSE)
write.table(format(calculated_values, scientific=FALSE), file="calculated_nosci.txt", row.names=FALSE, col.names=FALSE)
write.table(stock_data, file="stock_data.txt", row.names=FALSE, col.names=FALSE)

proc.time() - ptm1
````