---
title: "STAT 297 Homework 2"
author: "Austin Gongora, Ian Willick, Ciara Virgo, Mark Hancharik"
date: "October 13, 2017"

output: 
  html_document:
    theme: paper    
    highlight: tango 
    toc: true
    toc_depth: 3
    toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Fizz Buzz 







```{r,  echo=FALSE}

u = 10^4

results <- vector(mode = "character", length = u)

 for(i in 1:u) {
  x = i
  
    if (x %% (3 * 5) == 0){    # shortened from this:  if (x %% 3 == 0 & x %% 5 == 0){
      results[i] <- "fizz buzz"
      }else if (x %% 3 == 0){
      results[i] <- "fizz"
      }else if (x %% 5 == 0){
      results[i]  <- "buzz"
      }else{
      results[i]  <- i
    }

 }


num <- 45
cat("showing the last",num,"of",u)
tail(results, n=num) 

```

## Map


```{r,  echo=FALSE, message=FALSE}

library(ggmap)


uni_coord <- read.table("uni_coord.txt")



central_map <- get_map(location = 'Indiana', zoom = 5, maptype = "terrain")
ggmap(central_map) + geom_point(data = uni_coord, aes(V1, V2 ,col = V4), size= 3) +  xlab("Longitude") + ylab("Latitude")


```






## 3D-random walks

### a = (1/6), B = 10^4, seed = 1982
```{r, echo=FALSE, message=FALSE}

# a = (1/6), B = 10^4, seed = 1982:

timesToRun = 1

# set the size of the walk
walkSize = 10^4

#create a location vector to store x,y,z values
location <- c("X Axis" = 0, "Y Axis" = 0, "Z Axis" = 0)

# create a matrix to store the location points
path <- matrix(NaN, walkSize+1, 3, byrow=TRUE)
colnames(path) <- c("x1","y1","z1")

#add the start point to the path
path[1,] <- c(location[1],location[2],location[3])




# start a loop to run it n times and get n random endpoints
# create a matrix to store the location endpoints
endpoints <- matrix(NaN, timesToRun, 3, byrow=TRUE)
 for(j in 1:timesToRun) {

   
   
# here we generate the random walk numbers for the six possible moves
B <- walkSize
set.seed(1982)
Ut <- runif(B)

#boxOfNumbers <- c(sample(1:6, walkSize, replace=TRUE)) # replace = TRUE to allow for repeat numbers  
# instead of generating ints, generate a double between 0-1 and convert to an int
boxOfNumbers <- vector(mode = "integer", length = walkSize)  


for(i in 1:walkSize){
  currentNumber <- Ut[i] #runif(1)
  if(currentNumber <= (1/6)){
    boxOfNumbers[i] <- 1
  }else if(currentNumber <= (2/6)){
    boxOfNumbers[i] <- 2
  }else if(currentNumber <= (3/6)){
    boxOfNumbers[i] <- 3
  }else if(currentNumber <= (4/6)){
    boxOfNumbers[i] <- 4
  }else if(currentNumber <= (5/6)){
    boxOfNumbers[i] <- 5
  }else{
    boxOfNumbers[i] <- 6
  }

}   
   
# and we convert those moves to xyz coordinates here:
 for(i in 1:walkSize) { # set this from 2 instead of one because 1 is our starting point
   
   switch(boxOfNumbers[i],
       location[1] <- location[1] + 1,
       location[1] <- location[1] - 1,
       location[2] <- location[2] + 1,
       location[2] <- location[2] - 1,
       location[3] <- location[3] + 1,
       location[3] <- location[3] - 1
     
   )
    path[i+1,] <- c(location[1],location[2],location[3])
 } #end for(i in 1:walkSize) 

# add the endpoint  
 endpoints[j,] <- c(location[1],location[2],location[3])
 

 
 
 
 #reset origin to [0,0,0]
 #location[1] <- 0
 #location[2] <- 0
 #location[3] <- 0
} # end ten loop

# https://stackoverflow.com/questions/77434/how-to-access-the-last-value-in-a-vector#83222
#head(path, n=1)
#tail(path, n=1)


#write.table(path, file="path.txt")
library(plotly)

#data <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/_3d-line-plot.csv')
#path <- read.csv("path.csv")
p <- plot_ly(as.data.frame(path), x = ~x1, y = ~y1, z = ~z1, type = 'scatter3d', mode = 'lines', line = list(color = 'black', width = 1), name = 'path') %>%
  add_markers(x = 0, y = 0, z = 0, marker=list(color="red" , size=10 , opacity=1.0), name = 'start point')%>%
  add_markers(x = location[1], y = location[2], z = location[3], marker=list(color="blue" , size=10 , opacity=1.0), name = 'end point')  %>%
  layout(legend = list(x = 100, y = 0.5)) %>% 
 layout(annotations = 
 list(x = 1, y = -0.1, text = "a = (1/6), B = 10^4, seed = 1982", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='auto', yanchor='auto', xshift=0, yshift=0,
      font=list(size=15, color="black"))
 )
p



#write.csv(path, file="path.csv")
# print some things out to see if it's working...
#endpoints

#head(Ut)
#print("0.7533571 0.6056869 0.4977858 0.6473441 0.2183902 0.4594699 <-- expected value")
#boxOfNumbers
#path


 

```

### a = (.99)(1/6), B = 10^5, seed = 2000
```{r, echo=FALSE, message=FALSE}
# a = (.99)(1/6), B = 10^5, seed = 2000:

timesToRun = 1

# set the size of the walk
walkSize = 10^5

#create a location vector to store x,y,z values
location <- c("X Axis" = 0, "Y Axis" = 0, "Z Axis" = 0)

# create a matrix to store the location points
path <- matrix(NaN, walkSize+1, 3, byrow=TRUE)
colnames(path) <- c("x1","y1","z1")
#add the start point to the path
path[1,] <- c(location[1],location[2],location[3])




# start a loop to run it n times and get n random endpoints
# create a matrix to store the location endpoints
endpoints <- matrix(NaN, timesToRun, 3, byrow=TRUE)
 for(j in 1:timesToRun) {

   
   
# here we generate the random walk numbers for the six possible moves
B <- walkSize
set.seed(2000)
Ut <- runif(B)

#boxOfNumbers <- c(sample(1:6, walkSize, replace=TRUE)) # replace = TRUE to allow for repeat numbers  
   # instead of generating ints, generate a double between 0-1 and convert to an int
boxOfNumbers <- vector(mode = "integer", length = walkSize)  


for(i in 1:walkSize){
  currentNumber <- Ut[i] #runif(1)
  if(currentNumber <= ((1/6)*.99)){
    boxOfNumbers[i] <- 1
  }else if(currentNumber <= ((2/6)*.99)){
    boxOfNumbers[i] <- 2
  }else if(currentNumber <= ((3/6)*.99)){
    boxOfNumbers[i] <- 3
  }else if(currentNumber <= ((4/6)*.99)){
    boxOfNumbers[i] <- 4
  }else if(currentNumber <= ((5/6)*.99)){
    boxOfNumbers[i] <- 5
  }else{
    boxOfNumbers[i] <- 6
  }

}  
   
# and we convert those moves to xyz coordinates here:
 for(i in 1:walkSize) { # set this from 2 instead of one because 1 is our starting point
   
   switch(boxOfNumbers[i],
       location[1] <- location[1] + 1,
       location[1] <- location[1] - 1,
       location[2] <- location[2] + 1,
       location[2] <- location[2] - 1,
       location[3] <- location[3] + 1,
       location[3] <- location[3] - 1
     
   )
    path[i+1,] <- c(location[1],location[2],location[3])
 } #end for(i in 1:walkSize) 

# add the endpoint  
 endpoints[j,] <- c(location[1],location[2],location[3])
 #reset origin to [0,0,0]
# location[1] <- 0
 #location[2] <- 0
# location[3] <- 0
} # end ten loop
#endpoints


# https://stackoverflow.com/questions/77434/how-to-access-the-last-value-in-a-vector#83222
#head(path, n=1)
#tail(path, n=1)


p <- plot_ly(as.data.frame(path), x = ~x1, y = ~y1, z = ~z1, type = 'scatter3d', mode = 'lines', line = list(color = 'black', width = 1), name = 'path') %>%
  add_markers(x = 0, y = 0, z = 0, marker=list(color="red" , size=10 , opacity=1.0), name = 'start point')%>%
  add_markers(x = location[1], y = location[2], z = location[3], marker=list(color="blue" , size=10 , opacity=1.0), name = 'end point')  %>%
  layout(legend = list(x = 100, y = 0.5)) %>% 
 layout(annotations = 
 list(x = 1, y = -0.1, text = "a = (.99)(1/6), B = 10^5, seed = 2000", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0,
      font=list(size=15, color="black"))
 )
p
#p <- plot_ly(as.data.frame(path), x = ~x1, y = ~y1, z = ~z1, type = 'scatter3d', mode = 'lines', line = list(color = '#1f77b4', width = 1)) 
#p
# print out the expected value
#print("[142, -133, -899]")
```


## Construct a portfolio

### Our advice is to invest in Real Estate.

```{r, echo=FALSE}


 sp500names <- c( "ABT","ABBV","ACN","ATVI","AYI","ADBE","AMD","AAP",
 "AES","AET","AMG","AFL","A","APD","AKAM","ALK",
 "ALB","ARE","ALXN","ALGN","ALLE","AGN","ADS","LNT",
 "ALL","GOOGL", "GOOG","MO", "AMZN","AEE","AAL","AEP",
 "AXP","AIG","AMT","AWK","AMP","ABC","AME","AMGN", 
 "APH","APC","ADI","ANDV","ANSS","ANTM","AON","AOS",
 "APA","AIV","AAPL","AMAT","ADM","ARNC","AJG","AIZ",
 "T","ADSK","ADP","AZO","AVB","AVY","BHGE","BLL",
 "BAC","BK", "BCR","BAX","BBT","BDX","BRK-B", "BBY",
 "BIIB","BLK","HRB","BA", "BWA","BXP","BSX","BHF",
 "BMY","AVGO","BF-B","CHRW","CA", "COG","CDNS","CPB",
 "COF","CAH","CBOE","KMX","CCL","CAT","CBG","CBS",
"CELG","CNC","CNP","CTL","CERN","CF", "SCHW","CHTR", 
 "CHK","CVX","CMG","CB", "CHD","CI", "XEC","CINF", 
 "CTAS","CSCO","C","CFG","CTXS","CLX","CME","CMS",
 "COH","KO", "CTSH","CL", "CMCSA", "CMA","CAG","CXO",
 "COP","ED", "STZ","COO","GLW","COST","COTY","CCI",
"CSRA","CSX","CMI","CVS","DHI","DHR","DRI","DVA",
 "DE", "DLPH","DAL","XRAY","DVN","DLR","DFS","DISCA",
 "DISCK", "DISH","DG", "DLTR","D","DOV","DWDP","DPS",
 "DTE","DRE","DUK","DXC","ETFC","EMN","ETN","EBAY", 
 "ECL","EIX","EW", "EA", "EMR","ETR","EVHC","EOG",
 "EQT","EFX","EQIX","EQR","ESS","EL", "ES", "RE",
 "EXC","EXPE","EXPD","ESRX","EXR","XOM","FFIV","FB",
 "FAST","FRT","FDX","FIS","FITB","FE", "FISV","FLIR", 
 "FLS","FLR","FMC","FL", "F","FTV","FBHS","BEN",
 "FCX","GPS","GRMN","IT", "GD", "GE", "GGP","GIS",
 "GM", "GPC","GILD","GPN","GS", "GT", "GWW","HAL",
 "HBI","HOG","HRS","HIG","HAS","HCA","HCP","HP",
 "HSIC","HSY","HES","HPE","HLT","HOLX","HD", "HON",
 "HRL","HST","HPQ","HUM","HBAN","IDXX","INFO","ITW",
 "ILMN","IR", "INTC","ICE","IBM","INCY","IP", "IPG",
"IFF","INTU","ISRG","IVZ","IRM","JEC","JBHT","SJM",
 "JNJ","JCI","JPM","JNPR","KSU","K","KEY","KMB",
"KIM","KMI","KLAC","KSS","KHC","KR", "LB", "LLL",
 "LH", "LRCX","LEG","LEN","LVLT","LUK","LLY","LNC",
"LKQ","LMT","L","LOW","LYB","MTB","MAC","M", 
"MRO","MPC","MAR","MMC","MLM","MAS","MA", "MAT",
 "MKC","MCD","MCK","MDT","MRK","MET","MTD","MGM",
 "KORS" , "MCHP" , "MU", "MSFT","MAA","MHK","TAP","MDLZ", 
 "MON","MNST","MCO","MS", "MOS","MSI","MYL","NDAQ", 
 "NOV","NAVI","NTAP","NFLX" , "NWL","NFX","NEM","NWSA",
 "NWS","NEE","NLSN" , "NKE","NI", "NBL","JWN","NSC",
 "NTRS","NOC","NRG","NUE","NVDA","ORLY","OXY","OMC",
"OKE","ORCL","PCAR","PKG","PH", "PDCO","PAYX","PYPL", 
"PNR","PBCT" , "PEP","PKI","PRGO","PFE","PCG","PM",
 "PSX","PNW","PXD","PNC","RL", "PPG","PPL","PX",
 "PCLN","PFG","PG", "PGR","PLD","PRU","PEG","PSA",
 "PHM","PVH","QRVO" , "PWR","QCOM","DGX","Q","RRC",
 "RJF","RTN","O","RHT","REG","REGN","RF", "RSG",
 "RMD","RHI","ROK","COL","ROP","ROST","RCL","CRM",
 "SBAC","SCG","SLB","SNI","STX","SEE","SRE","SHW",
 "SIG","SPG","SWKS","SLG","SNA","SO", "LUV","SPGI", 
 "SWK","SBUX","STT","SRCL","SYK","STI","SYMC","SYF",
 "SNPS","SYY","TROW","TGT","TEL","FTI","TXN","TXT",
 "TMO","TIF","TWX","TJX","TMK","TSS","TSCO","TDG",
 "TRV","TRIP","FOXA","FOX","TSN","UDR","ULTA","USB",
 "UA", "UAA","UNP","UAL","UNH","UPS","URI","UTX",
 "UHS","UNM","VFC","VLO","VAR","VTR","VRSN","VRSK", 
 "VZ", "VRTX","VIAB","V","VNO","VMC","WMT","WBA",
 "DIS","WM", "WAT","WEC","WFC","HCN","WDC","WU",
 "WRK","WY", "WHR","WMB","WLTW","WYN","WYNN","XEL",
 "XRX","XLNX","XL")

sp500vars <- c( 0.00017176341604879 , 0.000293227428049176 , 0.000145320474410346 
, 0.000365183843127639 , 0.000369091577678117 , 0.000207210822545031 
, 0.00179343648184444 , 0.000368684400164806 , 0.000294024754611657 
, 0.000230349435469944 , 0.000330320331565672 , 0.00010180855679447 
, 0.000188290300918623 , 0.000147739755933819 , 0.000476179449957337 
, 0.000339919688104852 , 0.000371248587587543 , 0.000139349700427822 
, 0.000561227178114395 , 0.000336006928418645 , 0.000159916023969164 
, 0.000341936991283806 , 0.000313328177181444 , 0.000125407556392817 
, 0.000106444032966768 , 0.000201104311219083 , 0.000204839481099262 
, 0.000112944902340021 , 0.000322840651892323 , 0.000123939928382731 
, 0.000524722769941032 , 0.000116568319670464 , 0.000172150918478866 
, 0.000158861945997311 , 0.000140779315061483 , 0.000119379264549372 
, 0.000275092171089303 , 0.000225916894268223 , 0.000154245766494852 
, 0.000248455735470167 , 0.000137431584137761 , 0.000638083565006726 
, 0.000278072018564622 , 0.000451943863357803 , 0.000152578388003396 
, 0.000213358733798746 , 0.000106076894229553 , 0.000206295839172526 
, 0.000694740477784026 , 0.000158967546099341 , 0.000211615436852338 
, 0.000315965334975885 , 0.000241223357599896 , 0.000634280834088205 
, 9.07612755261579e-05 , 0.000191257775425085 , 9.38628329093252e-05 
, 0.000374841519258308 , 0.00014093616491878 , 0.000177256427092349 
, 0.0001230189846162 , 0.000163503771431445 , 0.000666973496434684 
, 0.000191038806995049 , 0.000286507155356952 , 0.000187062354598923 
, 0.000170316430887314 , 0.000138240774089218 , 0.000174255557141893 
, 0.000121599835996063 , 8.84843965582409e-05 , 0.000535312397934688 
, 0.000486744128305406 , 0.000181950380936806 , 0.000375000962425086 
, 0.000187818836812122 , 0.000382371632979621 , 0.000142710973368487 
, 0.00022817910620268 , 0.129433251720583 , 0.000269100158653392 
, 0.000451936507214482 , 0.000140136248639235 , 0.000171307960403305 
, 0.000184887484269818 , 0.000561213127070497 , 0.000204740577105609 
, 0.000138975358122238 , 0.000248024796673437 , 0.0002082217051224 
, 0.000124556217734996 , 0.000358883872261798 , 0.000240099936123222 
, 0.00025095375290491 , 0.000305864833753171 , 0.000218829173332968 
, 0.00036027915687395 , 0.000466648529984267 , 0.000163115173216483 
, 0.000333472874662396 , 0.000218997893001461 , 0.000683494764643022 
, 0.000349599332123316 , 0.000293113917105984 , 0.00255805510084119 
, 0.000217146696191452 , 0.000352859569093772 , 9.79159184970656e-05 
, 0.000103879054486066 , 0.000225855403799262 , 0.000543410419890706 
, 0.000111608317228463 , 0.000144652722970674 , 0.0001711332059133 
, 0.000259103035966888 , 0.000287387499019611 , 0.000297123577332338 
, 9.13531604102772e-05 , 0.000152066816726072 , 0.000118249024087801 
, 0.00033111718796759 , 7.49667986643161e-05 , 0.000265333783274248 
, 0.000103622596390979 , 0.000138827975881639 , 0.000320548444932571 
, 0.000169719469548314 , 0.000650431993506963 , 0.000469345894578143 
, 0.000113247190944461 , 0.000176418862301266 , 0.00019279156723818 
, 0.000201919079635948 , 0.00012806605425165 , 0.000470673653424674 
, 0.000121343761551464 , 0.000340736846603423 , 0.000339882325627404 
, 0.000240844437577469 , 0.000155106462853558 , 0.000291900521353125 
, 9.97492859499606e-05 , 0.000190875374962315 , 0.000154434307498519 
, 0.000211789097023663 , 0.000327747493213789 , 0.000367725851039864 
, 0.000156273878158868 , 0.000864995259342484 , 0.000172331029287855 
, 0.000187733402746556 , 0.000352081557387214 , 0.000321545315344356 
, 0.000312335488745658 , 0.000255422640672185 , 0.000271543926260227 
, 0.00010953711588101 , 0.000240370252534697 , 0.000241930188553571 
, 0.000112604015090185 , 0.00011338694244067 , 0.000147776872991362 
, 0.000112364457730952 , 0.000489214930960089 , 0.000372107111042457 
, 0.000239957232886912 , 0.000211125256488854 , 0.000266883925600001 
, 0.000136884075229777 , 0.000118180283054294 , 0.000362664136909712 
, 0.000324457366525728 , 0.000180597514495442 , 0.000132432138719163 
, 0.00059354865634205 , 0.000423837289096501 , 0.000450472323275113 
, 0.000218732060514287 , 0.000204094449527612 , 0.000141463187634258 
, 0.000137898681773035 , 0.000159017171986245 , 0.000118753852124915 
, 0.000120295054226954 , 0.000190908724090289 , 0.000377374401063908 
, 0.000133365662090524 , 0.000197720623324321 , 0.000187850735683523 
, 0.000147975201686218 , 0.000275655876385281 , 0.000245572558665074 
, 0.000223585844947512 , 0.000125683338685718 , 0.000178156771990644 
, 0.000164950233462422 , 0.000273513505978619 , 0.000185640789893758 
, 0.000113280282427446 , 0.000214951950412558 , 0.000345432777296973 
, 0.000339428920929384 , 0.000352201816872652 , 0.000428604685851054 
, 0.000211814028179521 , 0.000110070169282073 , 0.000195696614630346 
, 0.000236410494438756 , 0.0017411050625668 , 0.000501090360785274 
, 0.000297409185139953 , 0.00016930730628252 , 0.000119757004566559 
, 0.000139434354663731 , 0.000211630424651623 , 0.000110457387512542 
, 0.000235974407838772 , 0.000141018398019348 , 0.000308251261473152 
, 0.000267155078755965 , 0.000213928240107106 , 0.000321897045742943 
, 0.000198842582549118 , 0.000442916706537329 , 0.000383368218739052 
, 0.000359353987445716 , 0.00015886587422946 , 0.000162212995469799 
, 0.000263601643592371 , 0.000272637843315709 , 0.000237735942933497 
, 0.000692759507781165 , 0.000148202362848059 , 0.000164023742826519 
, 0.00062555705354664 , 0.000411484664392903 , 0.000231146760877085 
, 0.000230143249697017 , 0.000129223024097062 , 0.000119573484295334 
, 0.000176324194797102 , 0.000266637767775655 , 0.00035066763330608 
, 0.000293380145382414 , 0.000267329019211419 , 0.000314165934664241 
, 0.000190363282675218 , 0.000114953608033974 , 0.000641046556076913 
, 0.000173952859706866 , 0.00019154920734793 , 0.000166001400926651 
, 0.00014675036461425 , 0.000842329719218379 , 0.000213457398132792 
, 0.00021141049971625 , 0.000177772175311509 , 0.000191109667833555 
, 0.000171922710988655 , 0.000285851660217152 , 0.000214645687251191 
, 0.000252924029603361 , 0.00015864154262702 , 0.000143335367396639 
, 8.32579442599882e-05 , 0.000198323287003814 , 0.000186774048078917 
, 0.000310535446548631 , 0.000290726496733641 , 0.000115070829529008 
, 0.000284395458078181 , 0.000102803431861054 , 0.000193303127442046 
, 0.000495209468224601 , 0.000335197500560911 , 0.000549659269182342 
, 0.000176521682961485 , 0.000273549736289177 , 0.000385653649146378 
, 0.000159888833307246 , 0.000162076286270637 , 0.000307151036158133 
, 0.000155790881114506 , 0.000259963139212143 , 0.000266571850273173 
, 0.000238793865220401 , 0.000211770665448712 , 0.000353033589532759 
, 0.000213858437904009 , 9.7281332865144e-05 , 0.000103817820434768 
, 0.000179789285583682 , 0.00037305298308335 , 0.000191721231920764 
, 0.000215025127032557 , 0.00049676631841686 , 0.00106984397072076 
, 0.000486985835627059 , 0.000216320354862666 , 9.16167493358216e-05 
, 0.000384364905562999 , 0.000237207197185836 , 0.000158389840718232 
, 0.000400916294370733 , 0.000114057823716648 , 0.00010693094500324 
, 0.000311282639517121 , 0.000138560527513069 , 0.000156990718160121 
, 0.000273071018907978 , 0.000167465028366176 , 0.00043954973072426 
, 0.000610917302729 , 0.000265937924482352 , 0.00082800197525627 
, 0.000206116253783834 , 0.000141392714856358 , 0.000202112717006308 
, 0.000217577541868125 , 0.000196198081257237 , 0.000160701698422276 
, 0.000317613853035836 , 0.000177476058930209 , 0.000293048059250582 
, 0.00049477022274617 , 0.000159115331808162 , 0.000588118161889461 
, 0.000134983460600753 , 0.000527342559302974 , 0.000498834393819085 
, 0.000312219522731727 , 0.000768184960086887 , 0.000247438282119961 
, 0.000885287404681485 , 0.000735197470977312 , 0.000266355014768126 
, 0.000250490776553505 , 0.000113893392510177 , 0.000203793910363954 
, 0.000194867079474373 , 0.000157703487830628 , 0.00059654802093319 
, 0.00044344814624765 , 0.00025669006657768 , 0.000222958293237209 
, 0.000120866874270257 , 0.000922844878937159 , 0.000318818009250222 
, 0.000660939756227414 , 0.000249211914285068 , 0.000260708684541465 
, 0.000122356844501171 , 0.00068122457326349 , 0.000167047674961871 
, 0.000222517712480773 , 0.000278712438441898 , 0.000201517624983202 
, 0.000204201283414236 , 0.000114386532889395 , 0.000298381645946448 
, 0.00025451501813317 , 0.00015299502186082 , 7.0813699629339e-05 
, 0.000175324932460587 , 0.000503668736228506 , 0.000122399252910398 
, 0.000118682775708227 , 0.000111042419929916 , 0.000253566974311969 
, 0.0001127709986905 , 0.000539456263338287 , 0.000171074631474391 
, 0.000446437429368504 , 0.000178118946727446 , 0.00012113947572173 
, 0.000116504081122437 , 0.000273766024439154 , 0.00023952011317668 
, 7.87406641887852e-05 , 0.000106046449860694 , 0.000157225457045251 
, 0.000262313740184583 , 0.000147296098922581 , 0.000145543195514504 
, 0.000289769329448977 , 0.000368300953111307 , 0.000771742635167205 
, 0.00044257208798307 , 0.000312990979491619 , 0.000161061239811463 
, 0.0001895607734558 , 0.00102761028543538 , 0.000252174349648911 
, 0.000121525394707744 , 0.00016174034009619 , 0.000270330182620044 
, 0.000145128108446355 , 0.000500233643810899 , 0.000327808715360335 
, 7.87673321332857e-05 , 0.000240814114466188 , 0.000267550973945615 
, 0.000204256019575857 , 0.00015057057536215 , 0.000134685439053609 
, 0.000218516616328646 , 0.000434409100549864 , 0.000338850888336527 
, 0.000207910563359169 , 0.000164014900040308 , 0.000233361474496681 
, 0.000256533493009383 , 0.000775784425662334 , 0.000240935588882808 
, 0.000128323705605437 , 0.000188780051280163 , 0.000484970037248683 
, 0.000149549537380077 , 0.00053010818622147 , 0.000183725480781798 
, 0.000166397014744658 , 9.52875531467842e-05 , 0.000364519255395553 
, 0.000181094049609947 , 0.000135412410726588 , 0.000163501349505696 
, 0.000251367440073544 , 0.000313945518739393 , 0.000124204193353039 
, 0.000240515025542167 , 0.000271569150127054 , 0.000286021808026854 
, 0.000136419480481398 , 0.000120893165473413 , 0.000165292669759876 
, 0.000216029383736295 , 0.000168427285142869 , 0.000476391145323582 
, 0.00020752431331215 , 0.000252056259587621 , 0.0001598193610479 
, 0.000280541998517345 , 0.000166146408840273 , 0.00014939326929435 
, 0.000111676110809704 , 0.000230163924092742 , 0.000297175499331997 
, 0.000243447630481066 , 0.000100598375286073 , 0.000703973351555893 
, 0.000214272713838756 , 0.00021000052857217 , 0.000284570249240147 
, 0.000143788438553041 , 0.000302979544337864 , 0.000138254611162715 
, 0.00119156833241452 , 0.000579129253928805 , 0.000212292500207855 
, 0.000515305879120953 , 0.000163472516153194 , 0.000105159322744068 
, 0.000691483721648695 , 0.000118248573096395 , 0.000299086120584965 
, 0.000224187921999226 , 0.00021709492747037 , 0.00034501565300575 
, 0.000153176254680864 , 0.000255619860289009 , 0.000176777376666988 
, 0.0001424404216323 , 0.00010550400680214 , 0.000676710982821722 
, 0.000518985596858495 , 0.000164131674498791 , 0.000138884837685023 
, 0.000283673843760471 , 0.000138259957200904 , 0.00019955210790322 
, 0.000135707357830203 , 7.47976297361629e-05 , 0.000175768686441645 
, 0.000125096558011593 , 0.000168565426819488 , 0.000180318287768896 
, 0.000585896979136533 , 0.00019059510272455 , 0.00108511549476598 
, 0.000189971386752651 , 0.000299337345169552 , 0.00130721997299284 
, 0.000136425990138839 , 0.000217081421746863 , 0.000837829745768472 
, 0.000110943827322471 , 0.000335812971582424 , 0.000237318725023831 
, 0.000151146951522439 )


sp500means <- c(4.602262e-04,7.661429e-04,7.965925e-04,1.694113e-03,5.585162e-04
,1.200340e-03,2.697899e-03,-2.738847e-04,-1.714775e-04,1.076277e-03
,1.617455e-04,5.345115e-04,7.854753e-04,4.373832e-04,6.853684e-05
,1.006544e-03,1.315579e-03,7.107832e-04,5.259796e-05,1.994085e-03
,9.080071e-04,-4.407037e-05,6.441324e-05,5.899836e-04,6.178018e-04
,8.242436e-04,8.375882e-04,4.622496e-04,1.665597e-03,5.950497e-04
,8.027975e-04,4.561404e-04,1.792421e-04,3.425503e-04,5.981224e-04
,7.697323e-04,4.510921e-04,1.822115e-04,5.035982e-04,5.367326e-04
,8.255606e-04,-5.716939e-04,9.884105e-04,9.354778e-04,7.496074e-04
,7.642981e-04,7.694307e-04,1.371381e-03,-4.778140e-04,5.068011e-04
,7.047017e-04,1.407795e-03,-6.687157e-05,-5.393208e-05,4.654605e-04
,6.612452e-04,1.639468e-04,1.145871e-03,6.445988e-04,3.034869e-04
,3.650544e-04,1.203854e-03,-3.282206e-04,4.881666e-04,7.251319e-04
,5.740917e-04,1.111628e-03,7.056406e-04,4.097657e-04,6.381831e-04
,4.613043e-04,1.139437e-03,2.950231e-04,5.847912e-04,-3.349080e-05
,1.073361e-03,1.758671e-04,2.007924e-04,1.326958e-03,4.377851e-02
,4.863049e-04,1.692015e-03,3.587758e-04,2.928857e-04,4.006158e-04
,2.763789e-05,1.234063e-03,1.941357e-04,2.225278e-04,-5.646207e-05
,9.849159e-04,8.440779e-04,8.646584e-04,5.119673e-04,5.471860e-04
,2.565654e-04,7.203995e-04,1.424135e-03,3.004110e-04,-7.517137e-04
,3.854787e-04,-3.234964e-04,7.896260e-04,1.316066e-03,-8.556417e-04
,1.196592e-04,-8.368832e-04,4.846304e-04,4.656126e-04,1.120845e-03
,2.664081e-04,7.102479e-04,1.096094e-03,5.013020e-04,6.440049e-04
,8.185930e-04,6.649546e-04,4.289670e-04,7.936028e-04,6.347948e-04
,3.663682e-04,8.405141e-05,8.204877e-04,2.022518e-04,5.412668e-04
,7.673900e-04,4.471196e-04,5.346900e-04,-3.132691e-04,5.276133e-04
,1.285450e-03,6.977255e-04,7.306757e-04,3.660766e-04,2.772004e-04
,3.645247e-04,1.323086e-04,8.533795e-04,4.948289e-04,1.112369e-05
,1.050204e-03,6.525442e-04,8.770954e-04,-1.879627e-04,7.265034e-04
,7.879879e-04,6.973885e-04,4.174147e-04,-3.307318e-04,9.318621e-04
,1.400342e-04,-5.176661e-04,-5.778298e-04,-7.912424e-05,4.930972e-04
,7.411927e-04,1.741645e-04,3.883935e-04,6.012929e-04,4.779495e-04
,5.002075e-04,7.625401e-04,2.126953e-04,1.906119e-03,1.131534e-03
,3.300676e-04,4.109471e-04,8.668993e-04,2.878422e-04,4.748917e-04
,1.164004e-03,1.794273e-03,1.471130e-04,8.064041e-05,-7.778139e-04
,2.468723e-04,-1.977105e-04,6.768436e-04,1.156103e-03,1.492197e-04
,5.640967e-04,5.980266e-04,4.249191e-04,5.004015e-04,2.188611e-04
,9.241400e-04,6.309015e-04,-4.624169e-05,6.811422e-04,-1.027052e-04
,1.496455e-04,1.198911e-03,1.468331e-04,1.430534e-04,5.472512e-04
,7.851649e-04,6.137269e-04,1.661552e-06,9.851320e-04,5.407082e-04
,-3.903418e-04,-3.565029e-04,8.426717e-04,-3.918015e-04,-7.372668e-05
,1.271309e-03,7.637972e-04,-1.191860e-04,-1.861906e-04,-1.914365e-04
,2.436981e-04,7.426123e-04,8.086454e-04,4.635324e-05,-2.432225e-05
,8.716684e-05,5.744099e-04,2.019679e-04,-1.593410e-04,1.378503e-03
,4.926396e-04,6.977686e-04,-3.324903e-04,-1.926752e-04,8.156322e-06
,-1.186704e-04,1.059068e-03,6.433510e-04,8.766277e-04,2.379110e-04
,-2.841012e-04,-3.736570e-04,5.340700e-04,2.918721e-04,-5.935080e-04
,1.072967e-03,5.719152e-04,7.070730e-04,8.375714e-04,6.878160e-04
,3.800304e-04,-4.108025e-05,5.082472e-04,1.047301e-03,6.289139e-04
,1.430684e-03,1.066723e-03,8.749982e-04,6.711838e-04,7.459370e-04
,3.192904e-04,8.294561e-04,-2.402024e-04,1.607382e-03,3.751383e-04
,3.682683e-04,6.803614e-04,8.349541e-04,1.157956e-03,4.449003e-05
,3.203940e-04,4.213703e-04,5.799658e-04,1.636367e-04,3.893702e-04
,-6.460197e-05,7.437349e-04,5.395319e-04,-1.179462e-05,1.052928e-04
,6.082439e-04,2.075860e-04,-8.879132e-05,-6.776482e-04,5.741007e-04
,-1.003231e-04,2.085629e-04,-1.891565e-04,-3.711777e-04,7.885507e-04
,6.459024e-04,1.380250e-03,5.445576e-04,5.774257e-04,4.489964e-04
,2.633125e-04,5.087766e-04,6.822321e-04,5.498441e-04,8.470029e-04
,2.775434e-04,6.603537e-04,1.813902e-04,4.826377e-04,-6.051096e-05
,-1.086886e-03,-7.552556e-04,6.760638e-04,8.048064e-04,6.898785e-04
,9.258973e-04,9.917869e-04,9.741270e-04,-7.279226e-04,5.553710e-04
,7.703526e-04,-1.645361e-04,3.626233e-04,2.087264e-04,3.284058e-04
,1.347034e-03,6.771514e-04,-3.073334e-04,1.074832e-03,7.040687e-04
,7.803785e-04,7.207117e-04,9.682525e-04,2.763866e-04,3.527274e-04
,2.133012e-04,9.311991e-04,6.590133e-04,6.493829e-04,-6.823944e-04
,5.982680e-04,-6.264117e-05,8.409100e-04,-7.189520e-04,-1.694586e-04
,2.980275e-04,1.850516e-03,4.555495e-04,3.033179e-04,1.060065e-03
,-6.789102e-05,-2.875297e-05,6.666682e-04,8.452146e-05,3.271965e-04
,6.837086e-04,-7.514981e-04,-3.663626e-04,3.739571e-04,5.561184e-04
,1.192608e-03,1.841213e-04,2.979682e-04,3.380701e-03,5.796815e-04
,-3.357161e-04,2.376181e-04,1.969366e-04,3.870820e-04,4.488016e-04
,9.616213e-04,7.344564e-04,-9.445681e-06,5.484066e-04,1.178852e-03
,2.488474e-04,4.162827e-04,2.608686e-04,7.676323e-04,-4.704019e-04
,3.582214e-04,6.400134e-04,4.275123e-04,3.683298e-04,6.273215e-04
,1.100680e-05,7.315483e-04,-5.826877e-04,3.470501e-04,2.944228e-04
,2.425198e-04,8.621328e-04,4.916543e-04,1.777011e-04,9.381658e-04
,8.038368e-04,4.721202e-04,3.953158e-04,4.089207e-04,6.841407e-04
,2.636424e-04,4.293872e-04,3.536914e-04,-2.851054e-04,6.660122e-04
,8.373478e-04,-1.034906e-03,7.987224e-04,9.504417e-04,5.014259e-04
,1.094915e-03,2.614196e-04,6.213537e-04,7.376221e-04,7.093485e-04
,6.791099e-04,2.189430e-04,8.202752e-04,8.127264e-04,8.115409e-04
,8.547146e-04,1.124693e-03,8.646058e-04,4.847660e-04,8.497191e-05
,-3.633241e-04,2.798383e-04,-2.534576e-04,5.227980e-04,1.321039e-04
,8.826275e-04,-4.516382e-04,4.118234e-05,1.183622e-03,1.404781e-04
,3.909370e-04,2.017949e-04,9.699962e-04,9.707230e-04,8.624541e-04
,6.096748e-04,5.574962e-04,-4.818028e-04,8.453335e-04,7.749230e-04
,6.427007e-04,4.514528e-04,1.051635e-03,5.632666e-04,3.240772e-04
,1.081683e-05,6.616024e-04,-6.162968e-04,1.010676e-03,7.664953e-04
,7.294726e-04,1.554404e-04,5.359987e-04,3.517184e-04,6.517595e-04
,1.175843e-03,1.864583e-04,6.236859e-04,4.329740e-04,-6.284378e-04
,-1.841761e-04,-1.737663e-04,8.621583e-04,5.074445e-04,1.024246e-03
,4.506051e-04,-2.132054e-03,-5.793335e-04,1.968199e-04,7.345919e-04
,1.213558e-03,3.164682e-04,8.204615e-04,2.616254e-04,2.056899e-04
,7.116659e-04,1.091321e-04,8.839934e-04,5.852762e-04,-2.821217e-05
,1.004116e-03,5.134191e-04,2.938021e-05,8.747917e-04,-1.054108e-03
,1.032458e-03,1.763252e-04,1.122203e-03,9.807686e-05,3.679472e-04
,2.514915e-04,6.856063e-04,9.523357e-04,5.563101e-04,1.954301e-04
,1.883909e-04,1.519193e-04,3.589092e-04,3.899185e-04,1.899682e-04
,4.735757e-04,-1.116925e-04,5.502409e-04,5.313901e-04,1.156840e-04
,6.244714e-04,1.383566e-04,8.777210e-04,3.212232e-04)


cat("name vector length = ", length(sp500names), "\n")
cat("average variance vector length = ", length(sp500vars), "\n")
cat("mean return vector length = ", length(sp500means), "\n")
```

